# _config.yml
title: The Messianic Mission
description: Protecting God's People - 501(c)(3)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://themessianicmission.github.io" # the base hostname & protocol for your site
theme: minima
